package CustomerGUI;


import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.WindowEvent;


public class CustomerLanding extends javax.swing.JFrame {

    /**
     * Creates new form CustomerLanding
     */
    public CustomerLanding() {
        initComponents();
    }
    
    // close the previous window 
    public void close(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        landing = new javax.swing.JPanel();
        comeSpend = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        ahoy = new javax.swing.JLabel();
        restaurantFront1 = new javax.swing.JLabel();
        everybodySmile = new javax.swing.JLabel();
        krabbyP = new javax.swing.JLabel();
        kelpShake = new javax.swing.JLabel();
        coralBits = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        conch = new javax.swing.JLabel();
        disclaimer = new javax.swing.JLabel();
        disclaim3 = new javax.swing.JLabel();
        contact = new javax.swing.JLabel();
        email1 = new javax.swing.JLabel();
        disclaim1 = new javax.swing.JLabel();
        disclaim2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pop3 = new javax.swing.JLabel();
        pop1 = new javax.swing.JLabel();
        pop2 = new javax.swing.JLabel();
        contact1 = new javax.swing.JLabel();
        contact2 = new javax.swing.JLabel();
        contact3 = new javax.swing.JLabel();
        menu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 153, 255));

        landing.setBackground(new java.awt.Color(51, 153, 255));

        comeSpend.setBackground(new java.awt.Color(255, 255, 255));
        comeSpend.setFont(new java.awt.Font("High Tower Text", 1, 18)); // NOI18N
        comeSpend.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        comeSpend.setText("Come spend yer money here!");

        welcome.setBackground(new java.awt.Color(255, 255, 255));
        welcome.setFont(new java.awt.Font("Goudy Stout", 1, 24)); // NOI18N
        welcome.setForeground(new java.awt.Color(255, 228, 181));
        welcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcome.setText("Welcome to the Krusty Krab");

        ahoy.setBackground(new java.awt.Color(255, 255, 255));
        ahoy.setFont(new java.awt.Font("Goudy Stout", 1, 18)); // NOI18N
        ahoy.setForeground(new java.awt.Color(255, 228, 181));
        ahoy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ahoy.setText("Ahoy!");

        restaurantFront1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/storefront.png"))); // NOI18N

        everybodySmile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/everybody.png"))); // NOI18N

        krabbyP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kp.png"))); // NOI18N

        kelpShake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kelpShake.png"))); // NOI18N

        coralBits.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/coralBits.png"))); // NOI18N

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo.png"))); // NOI18N

        conch.setFont(new java.awt.Font("High Tower Text", 0, 18)); // NOI18N
        conch.setForeground(new java.awt.Color(255, 255, 255));
        conch.setText("Conch: 1-800-Krab");

        disclaimer.setFont(new java.awt.Font("High Tower Text", 1, 24)); // NOI18N
        disclaimer.setForeground(new java.awt.Color(255, 255, 255));
        disclaimer.setText("DISCLAIMER:");

        disclaim3.setFont(new java.awt.Font("High Tower Text", 0, 18)); // NOI18N
        disclaim3.setForeground(new java.awt.Color(255, 255, 255));
        disclaim3.setText("Duplication of its formula is punishible by law. Resitrictions apply. Results may vary");

        contact.setFont(new java.awt.Font("High Tower Text", 1, 24)); // NOI18N
        contact.setForeground(new java.awt.Color(255, 255, 255));
        contact.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        contact.setText("- Gene Scallop");

        email1.setFont(new java.awt.Font("High Tower Text", 0, 18)); // NOI18N
        email1.setForeground(new java.awt.Color(255, 255, 255));
        email1.setText("Email: krustykrab@bikinibottom.com");

        disclaim1.setFont(new java.awt.Font("High Tower Text", 0, 18)); // NOI18N
        disclaim1.setForeground(new java.awt.Color(255, 255, 255));
        disclaim1.setText("The krabby patty formula is the sole property of The Krusty Krab and");

        disclaim2.setFont(new java.awt.Font("High Tower Text", 0, 18)); // NOI18N
        disclaim2.setForeground(new java.awt.Color(255, 255, 255));
        disclaim2.setText("may only be discussed in part or in whole with its creator, Mr. Krabs.");

        jLabel4.setFont(new java.awt.Font("Goudy Stout", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 228, 181));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("POPULAR ITEMS");

        pop3.setFont(new java.awt.Font("High Tower Text", 1, 24)); // NOI18N
        pop3.setForeground(new java.awt.Color(255, 182, 193));
        pop3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pop3.setText("Coral Bits");

        pop1.setFont(new java.awt.Font("High Tower Text", 1, 24)); // NOI18N
        pop1.setForeground(new java.awt.Color(255, 182, 193));
        pop1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pop1.setText("Krabby Patty");

        pop2.setFont(new java.awt.Font("High Tower Text", 1, 24)); // NOI18N
        pop2.setForeground(new java.awt.Color(255, 182, 193));
        pop2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pop2.setText("Kelp Shake");

        contact1.setFont(new java.awt.Font("High Tower Text", 1, 24)); // NOI18N
        contact1.setForeground(new java.awt.Color(255, 255, 255));
        contact1.setText("Contact Us:");

        contact2.setFont(new java.awt.Font("High Tower Text", 1, 24)); // NOI18N
        contact2.setForeground(new java.awt.Color(255, 255, 255));
        contact2.setText("100% Customer Satisfaction!");

        contact3.setFont(new java.awt.Font("High Tower Text", 1, 24)); // NOI18N
        contact3.setForeground(new java.awt.Color(255, 255, 255));
        contact3.setText("\"Best food in Bikini Bottom!\"");

        menu.setBackground(new java.awt.Color(204, 204, 255));
        menu.setFont(new java.awt.Font("High Tower Text", 0, 36)); // NOI18N
        menu.setText("MENU");
        menu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMouseClicked(evt);
            }
        });
        menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout landingLayout = new javax.swing.GroupLayout(landing);
        landing.setLayout(landingLayout);
        landingLayout.setHorizontalGroup(
            landingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(landingLayout.createSequentialGroup()
                .addGap(500, 500, 500)
                .addComponent(ahoy))
            .addGroup(landingLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(landingLayout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(comeSpend, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(landingLayout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(restaurantFront1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(landingLayout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addGroup(landingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(landingLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(landingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pop1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pop2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(100, 100, 100)
                .addComponent(krabbyP))
            .addGroup(landingLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(landingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contact2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contact3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(140, 140, 140)
                .addGroup(landingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(landingLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(pop3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(130, 130, 130)
                .addComponent(kelpShake, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(coralBits, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(landingLayout.createSequentialGroup()
                .addComponent(everybodySmile)
                .addGroup(landingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contact1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(landingLayout.createSequentialGroup()
                        .addGroup(landingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(disclaimer, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(landingLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(landingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(disclaim1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(disclaim2, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(70, 70, 70)
                        .addComponent(logo))
                    .addGroup(landingLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(landingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(email1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(conch, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(disclaim3, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        landingLayout.setVerticalGroup(
            landingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(landingLayout.createSequentialGroup()
                .addComponent(ahoy)
                .addGap(4, 4, 4)
                .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(comeSpend, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(restaurantFront1)
                .addGap(10, 10, 10)
                .addGroup(landingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(landingLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(pop1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(pop2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(landingLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(krabbyP)))
                .addGap(10, 10, 10)
                .addGroup(landingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(landingLayout.createSequentialGroup()
                        .addComponent(contact2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(landingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(landingLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(contact, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(contact3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(landingLayout.createSequentialGroup()
                        .addComponent(pop3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(menu, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(kelpShake, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(landingLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(coralBits, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(landingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(landingLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(everybodySmile))
                    .addGroup(landingLayout.createSequentialGroup()
                        .addComponent(contact1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(email1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(conch, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(landingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(landingLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(disclaimer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(disclaim1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, 0)
                                .addComponent(disclaim2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(disclaim3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(landing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(landing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuActionPerformed

    }//GEN-LAST:event_menuActionPerformed

    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked
        close();
        CustomerGUI newFrame = new CustomerGUI();
        newFrame.setVisible(true);
    }//GEN-LAST:event_menuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerLanding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerLanding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerLanding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerLanding.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerLanding().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ahoy;
    private javax.swing.JLabel comeSpend;
    private javax.swing.JLabel conch;
    private javax.swing.JLabel contact;
    private javax.swing.JLabel contact1;
    private javax.swing.JLabel contact2;
    private javax.swing.JLabel contact3;
    private javax.swing.JLabel coralBits;
    private javax.swing.JLabel disclaim1;
    private javax.swing.JLabel disclaim2;
    private javax.swing.JLabel disclaim3;
    private javax.swing.JLabel disclaimer;
    private javax.swing.JLabel email1;
    private javax.swing.JLabel everybodySmile;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel kelpShake;
    private javax.swing.JLabel krabbyP;
    private javax.swing.JPanel landing;
    private javax.swing.JLabel logo;
    private javax.swing.JButton menu;
    private javax.swing.JLabel pop1;
    private javax.swing.JLabel pop2;
    private javax.swing.JLabel pop3;
    private javax.swing.JLabel restaurantFront1;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
